spring:
  application:
    name: donation-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:9036/donation_service}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root_psw}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    defer-datasource-initialization: true

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    baggage:
      remote-fields:
        - X-Request-Id
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER:http://localhost:9001/api/v2/spans}

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG   # si quer?s ver queries SQL

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:9061/eureka/}

mercado-pago:
  access-token: ${MERCADO_PAGO_ACCESS_TOKEN:APP_USR-6659598449973748-102510-4f1861533195bceafecbc1db62791db1-2946101252}
  url:
    success: ${MERCADO_PAGO_URL_SUCCESS:https://www.youtube.com/shorts/uS7Kcx9yMkQ}
    failure: ${MERCADO_PAGO_URL_FAILURE:https://www.youtube.com/watch?v=22z31vdqnWI}
    pending: ${MERCADO_PAGO_URL_PENDING:https://www.youtube.com/watch?v=mi_5tf9n7-Y}
    notify: ${MERCADO_PAGO_URL_NOTIFY:https://octennially-humanly-galileo.ngrok-free.dev/api/v1/webhooks/mercado-pago?source_news=webhooks}
